import ImgItem from "@/assets/images.svg";
import Profile from "@/assets/profleGit.jpg";
import CardItem from "@/components/commons/card-item";

export const productData = [
  {
    _id: "1",
    name: "Cropped Faux Leather Jacket",
    description: "A stylish cropped faux leather jacket perfect for any occasion",
    description_short: "Stylish cropped faux leather jacket",
    additional_info: "Material: Faux Leather, Care: Dry clean only",
    slug: "cropped-faux-leather-jacket",
    avatar: ImgItem,
    images: [ImgItem, Profile],
    sizeGuide: "Standard sizing chart applies",
    price: 29,
    finalPrice: 18.85, // Calculated with 35% discount
    discountType: "PERCENTAGE" as const,
    discount: 35,
    UNISEXTYPE: "UNISEX",
    variants: [],
    featured: true,
    categories: [],
    isFavorite: false,
    tag: "-35%",
    tagColor: "bg-red-500 text-white"
  },
  {
    _id: "2",
    name: "Satin Blouse",
    description: "Elegant satin blouse with a smooth finish",
    description_short: "Elegant satin blouse",
    additional_info: "Material: Satin, Care: Hand wash",
    slug: "satin-blouse",
    avatar: ImgItem,
    images: [ImgItem, ImgItem],
    sizeGuide: "Standard sizing chart applies",
    price: 77,
    finalPrice: 77,
    discountType: null,
    discount: 0,
    UNISEXTYPE: "UNISEX",
    variants: [],
    featured: false,
    categories: [],
    isFavorite: false,
    tag: "",
    tagColor: "bg-red-500"
  },
  {
    _id: "3",
    name: "Ribyr T-Shirt",
    description: "Comfortable ribbed t-shirt for everyday wear",
    description_short: "Comfortable ribbed t-shirt",
    additional_info: "Material: Cotton blend, Care: Machine wash",
    slug: "ribyr-t-shirt",
    avatar: ImgItem,
    images: [ImgItem, ImgItem, ImgItem],
    sizeGuide: "Standard sizing chart applies",
    price: 17,
    finalPrice: 17,
    discountType: null,
    discount: 0,
    UNISEXTYPE: "UNISEX",
    variants: [],
    featured: false,
    categories: [],
    isFavorite: false,
    tag: "",
    tagColor: ""
  },
  {
    _id: "4",
    name: "Cardigan Shirt",
    description: "Versatile cardigan shirt for layering",
    description_short: "Versatile cardigan shirt",
    additional_info: "Material: Cotton blend, Care: Machine wash",
    slug: "cardigan-shirt",
    avatar: ImgItem,
    images: [ImgItem, ImgItem],
    sizeGuide: "Standard sizing chart applies",
    price: 100,
    finalPrice: 89,
    discountType: "PERCENTAGE" as const,
    discount: 11,
    UNISEXTYPE: "UNISEX",
    variants: [],
    featured: true,
    categories: [],
    isFavorite: false,
    tag: "New",
    tagColor: "bg-white text-black"
  },
  {
    _id: "5",
    name: "Casual Jacket",
    description: "Stylish casual jacket for everyday wear",
    description_short: "Stylish casual jacket",
    additional_info: "Material: Cotton blend, Care: Machine wash",
    slug: "casual-jacket",
    avatar: ImgItem,
    images: [ImgItem, ImgItem],
    sizeGuide: "Standard sizing chart applies",
    price: 29,
    finalPrice: 29,
    discountType: null,
    discount: 0,
    UNISEXTYPE: "UNISEX",
    variants: [],
    featured: false,
    categories: [],
    isFavorite: false,
    tag: "Sale",
    tagColor: "bg-black text-white"
  },
  {
    _id: "6",
    name: "Shirt In Botanical Chinoshi Print",
    description: "Unique shirt featuring botanical Chinoshi print",
    description_short: "Botanical print shirt",
    additional_info: "Material: Cotton, Care: Machine wash",
    slug: "shirt-in-botanical-chinoshi-print",
    avatar: ImgItem,
    images: [ImgItem, ImgItem],
    sizeGuide: "Standard sizing chart applies",
    price: 82,
    finalPrice: 82,
    discountType: null,
    discount: 0,
    UNISEXTYPE: "UNISEX",
    variants: [],
    featured: false,
    categories: [],
    isFavorite: false,
    tag: "",
    tagColor: ""
  },
  {
    _id: "7",
    name: "Cotton Jersey T-Shirt",
    description: "Classic cotton jersey t-shirt for everyday comfort",
    description_short: "Classic cotton t-shirt",
    additional_info: "Material: Cotton jersey, Care: Machine wash",
    slug: "cotton-jersey-t-shirt",
    avatar: ImgItem,
    images: [ImgItem, ImgItem],
    sizeGuide: "Standard sizing chart applies",
    price: 17,
    finalPrice: 17,
    discountType: null,
    discount: 0,
    UNISEXTYPE: "UNISEX",
    variants: [],
    featured: false,
    categories: [],
    isFavorite: false,
    tag: "",
    tagColor: ""
  },
  {
    _id: "8",
    name: "Zessi Dresser",
    description: "Elegant Zessi dresser for special occasions",
    description_short: "Elegant Zessi dresser",
    additional_info: "Material: Premium blend, Care: Dry clean only",
    slug: "zessi-dresser",
    avatar: ImgItem,
    images: [ImgItem, ImgItem],
    sizeGuide: "Standard sizing chart applies",
    price: 100,
    finalPrice: 89,
    discountType: "PERCENTAGE" as const,
    discount: 11,
    UNISEXTYPE: "UNISEX",
    variants: [],
    featured: true,
    categories: [],
    isFavorite: false,
    tag: "",
    tagColor: ""
  }
];


const ListTrending = () => {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 md:gap-6 lg:gap-8 container max-w-7xl mx-auto">
      {productData.map((product) => (
        <CardItem key={product._id} product={product} />
      ))}
    </div>
  );
};

export default ListTrending;
